// Ship the interface only. Never generate demo data or publish invoice PDFs.
import { mkdir, copyFile, rm } from 'node:fs/promises';
const root = new URL('../../', import.meta.url);
const destination = new URL('frontend/public/desk/', root);
await mkdir(destination, { recursive: true });
await copyFile(new URL('desk/mock/index.html', root), new URL('index.html', destination));
await copyFile(new URL('desk/live.js', root), new URL('live.js', destination));
// These paths were generated by the retired demo exporter. Do not ship them.
await rm(new URL('sepa.xml', destination), { force: true });
await rm(new URL('facturas/', destination), { recursive: true, force: true });
